### ISSUE TITLE
z64compress won't let me recompress my OoT-randomizer ROM

### ISSUE THREAD

**Issue by fpi1337** [z64me/z64compress#4]
Hi,

as the title says I ran into an issue when recompressing my ROM. 

First I decompressed it using your z64decompress-tool by entering the command

`./z64decompress-v1.0.2-linux64 OoT_382DB_LDF1A5K77H-comp.z64 out2.z64`

After that, your decompressor gives me the following command to recompress my ROM:

`welcome to z64decompress 1.0.2 <z64.me>
extra features by @zel640
decompressed file 'out2.z64' written successfully
here are your z64compress arguments:
z64compress --in "out2.z64" --out "out.z64" --mb 32 --codec yaz --dma "0x7430,1526" --compress "0-END" --skip "0" --skip "1" --skip "2" --skip "3" --skip "4" --skip "5" --skip "6" --skip "7" --skip "8" --skip "9" --skip "15" --skip "16" --skip "17" --skip "18" --skip "19" --skip "20" --skip "21" --skip "22" --skip "23" --skip "24" --skip "25" --skip "26" --skip "942" --skip "944" --skip "946" --skip "948" --skip "950" --skip "952" --skip "954" --skip "956" --skip "958" --skip "960" --skip "962" --skip "964" --skip "966" --skip "968" --skip "970" --skip "972" --skip "974" --skip "976" --skip "978" --skip "980" --skip "982" --skip "984" --skip "986" --skip "988" --skip "990" --skip "992" --skip "994" --skip "996" --skip "998" --skip "1000" --skip "1002" --skip "1004" --skip "1498" --skip "1499" --skip "1500" --skip "1501" --skip "1502" --skip "1503" --skip "1504" --skip "1505" --skip "1506" --skip "1507" --skip "1508" --skip "1509" --skip "1510" --skip "1511" --skip "1512" --skip "1513" --skip "1514" --skip "1515" --skip "1516" --skip "1517" --skip "1518" --skip "1519" --skip "1520" --skip "1521" --skip "1522" --skip "1523" --skip "1524" --skip "1525"`.

When I enter this command (obviously I had to change the "z64compress" to "/z64compress-linux64) an error encounters, saying:

`welcome to z64compress <z64.me>
invalid dma entry encountered: 03491860 03494A18 03491860 00000000
`

How can I avoid this? Is the DMA given by the decompressor wrong?

Thank you in advance. :)

**Comment by z64me** [comment]
Thanks for the bug report! This has now been addressed in the [z64compress v1.0.1 release](https://github.com/z64me/z64compress/releases/tag/v1.0.1). 🎉

**Comment by fpi1337** [comment]
You're awesome (and fast as hell)! Thank you!!
