### ISSUE TITLE
`-march=native -mtune=native` do not work for some architectures

### ISSUE THREAD

**Issue by EllipticEllipsis** [z64me/z64compress#7]
Some architectures do not specify these flags in some compilers: I recently encountered this on an Apple arm64 machine, but others apparently exist: https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1 . Therefore z64compress could do with a way to turn these on and off without setting `CFLAGS` as an environment variable, to make it a bit more flexible should you want to `CFLAGS += ...` in the makefile in future.

A simple way would just be to add a makefile variable that projects can enable or disable. I'm not sure if there's a more sophisticated way that could do it automatically: possibly compile a very small test file first, and set the flags or not depending on the compiler output?

**Comment by z64me** [comment]
Thanks for the bug report! Now resolved by @Thar0 in PR #8
